CREATE DATABASE 5ItiaBGestireVendite;


use 5ItiaBGestireVendite;


CREATE table RAPPRESENTANTI(
	CodRappr VARCHAR(2) NOT NULL,
	Cognome VARCHAR(30) NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	Via VARCHAR(30) NOT NULL,
	Citta VARCHAR(30) NOT NULL,
	Provincia VARCHAR(30) NOT NULL,
	CAP VARCHAR(5) NOT NULL,
	TotProvvigioni INT UNSIGNED NOT NULL,
	PercentProvv DECIMAL(4,2) NOT NULL,


	PRIMARY KEY (CodRappr)
);


CREATE table CLIENTI(
	CodRappr VARCHAR(3),
	CodCliente VARCHAR(6) NOT NULL,	
	Cognome VARCHAR(30) NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	Via VARCHAR(30) NOT NULL,
	Citta VARCHAR(30) NOT NULL,
	Provincia VARCHAR(30) NOT NULL,
	CAP VARCHAR(5) NOT NULL,
	Saldo DECIMAL(8,2) NOT NULL, 
	Fido DECIMAL(8,2) NOT NULL,

	PRIMARY KEY (CodCliente),
	FOREIGN KEY (CodRappr)
		REFERENCES RAPPRESENTANTI(CodRappr)
);


CREATE table ORDINI(
	CodCliente VARCHAR(6) NOT NULL,
	NroOrdine SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
	DataOrdine DATE NOT NULL,

	PRIMARY KEY(NroOrdine),
	FOREIGN KEY (CodCliente)
		REFERENCES CLIENTI(CodCliente)
   
);


CREATE table ARTICOLI(
	NroArt INT UNSIGNED NOT NULL,
	Descrizione VARCHAR(200) NOT NULL,
	Giacenza DECIMAL(8,2) NOT NULL,
	Categoria VARCHAR(50) NOT NULL,
	PrezzoUnitario DECIMAL(9,2) NOT NULL,
	
	FOREIGN KEY(NroArt)
		REFERENCES DETTORDINI(NroArt)
);


CREATE table DETTORDINI(
	NroOrdine SMALLINT UNSIGNED NOT NULL,
	NroArt INT UNSIGNED NOT NULL,
	QtaOrd DECIMAL(8,2) NOT NULL,
	PrezzoRichiesto DECIMAL(9,2) NOT NULL,
	 
	PRIMARY KEY(NroOrdine, NroArt),
	FOREIGN KEY(NroOrdine) 
		REFERENCES ORDINI(NroOrdine),
	FOREIGN KEY(NroArt) 
		REFERENCES ARTICOLI(NroArt)
); 


